base:
  project: aissm_mlops
  random_state: 20
  target_col: charges

data_source:
  raw_dataset_csv: data/raw/insurance.csv

load_data:
  clean_data: data/processed/insurance1.csv

split_data:
  train_path: data/processed/train_aiss.csv
  train_path: data/processed/test_aiss.csv
  test_size: 0.2






